INSERT OR IGNORE INTO sports (id,name,slug,sort_order) VALUES
(1,'Baseball','baseball',1),(2,'Football','football',2),(3,'Basketball','basketball',3),(4,'Hockey','hockey',4);
INSERT OR IGNORE INTO manufacturers (id,name,slug) VALUES
(1,'Topps','topps'),(2,'Bowman','bowman'),(3,'Panini','panini'),(4,'Upper Deck','upper-deck'),(5,'Donruss','donruss'),(6,'Fleer','fleer'),(7,'Score','score'),(8,'Leaf','leaf');
INSERT OR IGNORE INTO affiliations (name,normalized_name,sport_id,league,type,aliases_json) VALUES
('New York Yankees','new york yankees',1,'MLB','team','["Yankees","NYY"]'),
('New York Mets','new york mets',1,'MLB','team','["Mets","NYM"]'),
('Los Angeles Dodgers','los angeles dodgers',1,'MLB','team','["Dodgers","LAD"]'),
('Chicago White Sox','chicago white sox',1,'MLB','team','["White Sox","CWS"]'),
('Miami Marlins','miami marlins',1,'MLB','team','["Marlins","MIA"]'),
('San Diego Padres','san diego padres',1,'MLB','team','["Padres","SD"]'),
('Boston Red Sox','boston red sox',1,'MLB','team','["Red Sox","BOS"]'),
('Kansas City Royals','kansas city royals',1,'MLB','team','["Royals","KC"]'),
('Houston Astros','houston astros',1,'MLB','team','["Astros","HOU"]'),
('Toronto Blue Jays','toronto blue jays',1,'MLB','team','["Blue Jays","TOR"]'),
('Chicago Cubs','chicago cubs',1,'MLB','team','["Cubs","CHC"]'),
('St. Louis Cardinals','st. louis cardinals',1,'MLB','team','["Cardinals","STL","St Louis Cardinals"]'),
('Pittsburgh Pirates','pittsburgh pirates',1,'MLB','team','["Pirates","PIT"]'),
('San Francisco Giants','san francisco giants',1,'MLB','team','["Giants","SF"]'),
('Washington Nationals','washington nationals',1,'MLB','team','["Nationals","WSH"]'),
('Angels','angels',1,'MLB','team','["Los Angeles Angels","LAA"]'),
('Athletics','athletics',1,'MLB','team','["Oakland Athletics","A’s","A''s","ATH"]'),
('Tampa Bay Rays','tampa bay rays',1,'MLB','team','["Rays","TB"]'),
('Cleveland Guardians','cleveland guardians',1,'MLB','team','["Guardians","CLE"]'),
('Philadelphia Phillies','philadelphia phillies',1,'MLB','team','["Phillies","PHI"]'),
('Arizona Diamondbacks','arizona diamondbacks',1,'MLB','team','["Diamondbacks","D-backs","ARI"]'),
('Detroit Tigers','detroit tigers',1,'MLB','team','["Tigers","DET"]'),
('Baltimore Orioles','baltimore orioles',1,'MLB','team','["Orioles","BAL"]'),
('Colorado Rockies','colorado rockies',1,'MLB','team','["Rockies","COL"]'),
('Texas Rangers','texas rangers',1,'MLB','team','["Rangers","TEX"]'),
('Minnesota Twins','minnesota twins',1,'MLB','team','["Twins","MIN"]'),
('Milwaukee Brewers','milwaukee brewers',1,'MLB','team','["Brewers","MIL"]'),
('Cincinnati Reds','cincinnati reds',1,'MLB','team','["Reds","CIN"]'),
('Seattle Mariners','seattle mariners',1,'MLB','team','["Mariners","SEA"]'),
('Atlanta Braves','atlanta braves',1,'MLB','team','["Braves","ATL"]'),
('Brooklyn Dodgers','brooklyn dodgers',1,'MLB','historical_team','["Brooklyn"]'),
('Montréal Expos','montreal expos',1,'MLB','historical_team','["Montreal Expos","Expos"]'),
('St. Louis Browns','st. louis browns',1,'MLB','historical_team','["St Louis Browns"]'),
('Washington Senators','washington senators',1,'MLB','historical_team','["Senators"]'),
('New York Giants','new york giants baseball',1,'MLB','historical_team','[]'),
('Florida Marlins','florida marlins',1,'MLB','historical_team','[]'),
('Penn State','penn state',1,'NCAA','college','["Penn State University"]');
