<script>
  import { extractPdfText } from '$lib/client/pdf.js'; import { parseChecklistText,groupByChecklist } from '$lib/client/checklist-parser.js';
  let { data } = $props();
  let year=$state(new Date().getFullYear()); let name=$state(''); let sportId=$state(); let manufacturerId=$state(); let sourceUrl=$state(''); let sourceFilename=$state('');
  let rawDialog=$state();
  $effect(() => {
    if (sportId == null) sportId = data.sports[0]?.id ?? 1;
    if (manufacturerId == null) manufacturerId = data.manufacturers[0]?.id ?? 1;
  });
  let text=$state(''); let parsed=$state(null); let busy=$state(false); let status=$state(''); let errorMessage=$state(''); let selected=$state(new Set());
  async function fileChanged(e){ const file=e.currentTarget.files?.[0]; if(!file)return; sourceFilename=file.name; errorMessage=''; busy=true; status='Reading PDF…'; try{text=await extractPdfText(file); status='Parsing checklist…'; parsed=parseChecklistText(text,data.affiliations); selected=new Set(parsed.cards.map((_,i)=>i)); status='';}catch(err){errorMessage=err?.message||'Could not read PDF.';}finally{busy=false;} }
  function parsePasted(){parsed=parseChecklistText(text,data.affiliations);selected=new Set(parsed.cards.map((_,i)=>i));}
  function toggle(i){const s=new Set(selected);s.has(i)?s.delete(i):s.add(i);selected=s;}
  async function importData(){ if(!parsed||!name)return; busy=true;status='Importing…';errorMessage=''; const cards=parsed.cards.filter((_,i)=>selected.has(i)); try{const r=await fetch('/api/import',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({year:Number(year),name,sportId:Number(sportId),manufacturerId:Number(manufacturerId),sourceUrl,sourceFilename,cards,checklistMeta:parsed.checklist_meta})});const out=await r.json();if(!r.ok)throw new Error(out.message||'Import failed');location.href=`/sets/${out.slug}`;}catch(err){errorMessage=err?.message||'Import failed';busy=false;status='';}}
  const groups=$derived(parsed?groupByChecklist(parsed.cards):{});
</script>
<svelte:head><title>Import checklist — setbound</title></svelte:head>
<section class="shell page"><div class="eyebrow">Admin</div><h1 class="h2">Import a checklist</h1><p class="intro">Upload a manufacturer PDF. Setbound extracts text in the browser, detects checklist sections, normalizes affiliations, flags NIL subjects, and now captures checklist-level parallel/odds text when the source provides it.</p>
<div class="form card-shell"><label>Sport<select class="input" bind:value={sportId}>{#each data.sports as s}<option value={s.id}>{s.name}</option>{/each}</select></label><label>Year<input class="input" type="number" bind:value={year}/></label><label>Manufacturer<select class="input" bind:value={manufacturerId}>{#each data.manufacturers as m}<option value={m.id}>{m.name}</option>{/each}</select></label><label class="wide">Product name<input class="input" bind:value={name} placeholder="Allen & Ginter"/></label><label class="wide">Official source URL <span>(optional)</span><input class="input" bind:value={sourceUrl} placeholder="https://…"/></label></div>
<div class="upload"><input id="pdf" type="file" accept="application/pdf" onchange={fileChanged}/><label for="pdf"><strong>{sourceFilename||'Drop in an official checklist PDF'}</strong><span>{busy?status:'PDF text is extracted locally before import.'}</span></label><div>or</div><button class="btn btn-secondary" onclick={()=>rawDialog?.showModal()}>Paste extracted text</button></div>
{#if errorMessage}<div class="error">{errorMessage}</div>{/if}
{#if parsed}<div class="summary"><div><strong>{parsed.cards.length.toLocaleString()}</strong><span>cards detected</span></div><div><strong>{parsed.sections.length}</strong><span>sections</span></div><div><strong>{parsed.metaSections||0}</strong><span>sections with details</span></div><div class="warn"><strong>{parsed.review}</strong><span>needs review</span></div></div>
<div class="review-head"><div><h2>Review import</h2><p>{selected.size.toLocaleString()} rows selected</p></div><button class="btn btn-accent" disabled={busy||!name} onclick={importData}>{busy?status:`Import ${selected.size.toLocaleString()} cards`}</button></div>
{#each Object.entries(groups) as [section,cards]}
  {@const meta=parsed.checklist_meta?.[section]}
  <details open>
    <summary><strong>{section}</strong><span>{cards.length} cards{meta?.parallels?.length ? ` · ${meta.parallels.length} parallel lines` : ''}</span></summary>
    {#if meta?.parallels?.length}<div class="meta-preview"><strong>Parallel details detected</strong>{#each meta.parallels as line}<span>{line}</span>{/each}</div>{/if}
    <div class="table-wrap"><table><thead><tr><th></th><th>#</th><th>Subject</th><th>Affiliation</th><th>Flags</th><th>Confidence</th></tr></thead><tbody>{#each cards as card}{@const i=parsed.cards.indexOf(card)}<tr class:low={card.confidence<.85}><td><input type="checkbox" checked={selected.has(i)} onchange={()=>toggle(i)}/></td><td>{card.card_number}</td><td><strong>{card.subject}</strong></td><td class:muted={card.affiliation==='NIL'}>{card.affiliation}</td><td>{card.rookie?'RC ':''}{card.autograph?'AU ':''}{card.memorabilia?'MEM ':''}</td><td>{Math.round(card.confidence*100)}%</td></tr>{/each}</tbody></table></div>
  </details>
{/each}{/if}
</section>
<dialog id="raw" bind:this={rawDialog}><form method="dialog"><div class="modal-head"><strong>Paste checklist text</strong><button>×</button></div><textarea bind:value={text} placeholder="BASE CARDS\n100 cards.\nParallels:\nGold /50\n...\n1 Francisco Lindor New York Mets\n…"></textarea><button class="btn btn-primary" onclick={parsePasted}>Parse text</button></form></dialog>
<style>.page{padding-top:4rem}.intro{color:var(--muted);max-width:760px;line-height:1.6}.form{display:grid;grid-template-columns:1fr .7fr 1fr;gap:1rem;padding:1.2rem;margin:2rem 0}.wide{grid-column:span 3}.wide span{font-weight:500}.upload{min-height:150px;border:1px dashed var(--line-strong);border-radius:1rem;display:flex;align-items:center;justify-content:center;gap:1rem;padding:1.5rem;background:#fafafa}.upload input{display:none}.upload label{cursor:pointer;display:flex;flex-direction:column;align-items:center;color:var(--ink)}.upload label span{font-weight:500;color:var(--muted);margin-top:.25rem}.upload>div{color:var(--muted);font-size:.75rem}.error{margin-top:1rem;padding:.8rem 1rem;background:#fff4ea;border:1px solid #f4c89f;border-radius:.7rem}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:.75rem;margin:1.5rem 0}.summary div{border:1px solid var(--line);border-radius:.8rem;background:white;padding:1rem}.summary strong,.summary span{display:block}.summary strong{font-size:1.5rem}.summary span{color:var(--muted);font-size:.75rem;font-weight:700}.summary .warn strong{color:#b66420}.review-head{display:flex;justify-content:space-between;align-items:end;margin:2.2rem 0 1rem}.review-head h2,.review-head p{margin:0}.review-head p{color:var(--muted);font-size:.8rem;margin-top:.2rem}details{margin:.7rem 0}summary{cursor:pointer;padding:.85rem 1rem;border:1px solid var(--line);border-radius:.7rem;background:white;display:flex;justify-content:space-between}summary span{color:var(--muted);font-size:.75rem}.meta-preview{border-left:2px solid var(--orange);margin:.8rem 1rem 1rem;padding:.15rem 0 .15rem .9rem;display:grid;gap:.28rem}.meta-preview strong{font-size:.76rem;text-transform:uppercase;letter-spacing:.08em}.meta-preview span{font-size:.78rem;color:var(--muted)}.low{background:#fff9f3}dialog{width:min(800px,calc(100% - 2rem));border:0;border-radius:1rem;padding:0;box-shadow:0 30px 90px rgba(0,0,0,.25)}dialog::backdrop{background:rgba(18,16,14,.45)}dialog form{padding:1rem}.modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:.8rem}.modal-head button{border:0;background:none;font-size:1.5rem;cursor:pointer}textarea{width:100%;min-height:360px;border:1px solid var(--line-strong);border-radius:.7rem;padding:.8rem;font:12px ui-monospace,monospace;margin-bottom:.8rem}@media(max-width:700px){.form{grid-template-columns:1fr 1fr}.wide{grid-column:span 2}.summary{grid-template-columns:1fr 1fr}.upload{flex-direction:column}.review-head{align-items:stretch;flex-direction:column;gap:1rem}}</style>
